/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author rd193379m
 */
public class RegistrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public RegistrationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        slika_lb = new javax.swing.JLabel();
        tekst_lb = new javax.swing.JLabel();
        ime_lb = new javax.swing.JLabel();
        prezime_lb = new javax.swing.JLabel();
        email_lb = new javax.swing.JLabel();
        lozinka_lb = new javax.swing.JLabel();
        korisnicko_ime_lb = new javax.swing.JLabel();
        ime_tf = new javax.swing.JTextField();
        prezime_tf = new javax.swing.JTextField();
        email_tf = new javax.swing.JTextField();
        korisnicko_ime_tf = new javax.swing.JTextField();
        lozinka_tf = new javax.swing.JPasswordField();
        registruj_se_btn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        slika_lb.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\AirlineReservationSystem\\slike\\korisnik2.png")); // NOI18N

        tekst_lb.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        tekst_lb.setText("REGISTRACIJA");

        ime_lb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ime_lb.setText("Ime");

        prezime_lb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        prezime_lb.setText("Prezime");

        email_lb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        email_lb.setText("Email");

        lozinka_lb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lozinka_lb.setText("Lozinka");

        korisnicko_ime_lb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        korisnicko_ime_lb.setText("Korisnicko ime");

        registruj_se_btn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        registruj_se_btn.setText("REGISTRUJ SE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tekst_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(registruj_se_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(prezime_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(ime_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(email_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(korisnicko_ime_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lozinka_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(47, 47, 47)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lozinka_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(korisnicko_ime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(prezime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 79, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(slika_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(slika_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(tekst_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ime_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(prezime_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prezime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(korisnicko_ime_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(korisnicko_ime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lozinka_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lozinka_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(registruj_se_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
        );

        setSize(1000, 600);
        setLocation(100, 10);
        setVisible(true);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel email_lb;
    private javax.swing.JTextField email_tf;
    private javax.swing.JLabel ime_lb;
    private javax.swing.JTextField ime_tf;
    private javax.swing.JLabel korisnicko_ime_lb;
    private javax.swing.JTextField korisnicko_ime_tf;
    private javax.swing.JLabel lozinka_lb;
    private javax.swing.JPasswordField lozinka_tf;
    private javax.swing.JLabel prezime_lb;
    private javax.swing.JTextField prezime_tf;
    private javax.swing.JButton registruj_se_btn;
    private javax.swing.JLabel slika_lb;
    private javax.swing.JLabel tekst_lb;
    // End of variables declaration                 

    public JTextField getEmail_tf() {
        return email_tf;
    }

    public JTextField getIme_tf() {
        return ime_tf;
    }

    public JTextField getKorisnicko_ime_tf() {
        return korisnicko_ime_tf;
    }

    public JPasswordField getLozinka_tf() {
        return lozinka_tf;
    }

    public JTextField getPrezime_tf() {
        return prezime_tf;
    }

    public JButton getRegistruj_se_btn() {
        return registruj_se_btn;
    }

}
